### ISSUE TITLE
Using two NVIDIA GPUs with all monitors ok in the first gpu, one is always black on second gpu. (Although the cursor does move between them and I can see it on the black monitor too - only wayland)

### ISSUE THREAD

**Issue by gilvbp** [NVIDIA/egl-wayland#152]
I'm using two GPUs, and while all the monitors are okay on the first GPU, one is always black (the cursor does move ok) on the second GPU (it works fine on Xorg). It's just Wayland's issue.

I'm facing this issue on (https://gitlab.gnome.org/GNOME/mutter/-/issues/3733) Gnome, although it also happens on KDE. I'm using the last 560 drivers. 

NVIDIA Forum issue link: https://forums.developer.nvidia.com/t/using-two-nvidia-gpus-monitor-ok-in-the-first-gpu-one-is-always-black-on-second-gpu-but-shows-mouse-cursor/309912

**Comment by gilvbp** [comment]
Will be fixed soon, address here: https://forums.developer.nvidia.com/t/wayland-support-for-the-565-release-series/312688

**Comment by gilvbp** [comment]
Closing has to be implemented by DE and  using Vulkan Direct to Display. Ref: https://forums.developer.nvidia.com/t/wayland-support-for-the-565-release-series/312688

**Comment by gilvbp** [comment]
@amshafer  @kbrenneman  I finally got some rendering on my second monitor GPU (also showing on nvtop), debugging/changing some code here https://github.com/NVIDIA/egl-wayland/issues/152. Could you guys help me? Thanks

**Comment by amshafer** [comment]
Sorry for forgetting to update here, we have a reproduction of this issue and are looking into it. I don't have a timeline for a fix yet unfortunately.

**Comment by gilvbp** [comment]
No problem. Thanks.

**Comment by dkorkmazturk** [comment]
Thanks for reporting this issue. It seems like this issue has multiple components. We identified the driver side issue and have a fix for it, which will be released in an upcoming NVIDIA driver release. That fix allows the second monitor to work on KWin 6.2.4. However, Mutter needs some compositor side changes on top of the driver fix we have implemented. The required change can be found at https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4182.

**Comment by gilvbp** [comment]
> Thanks for reporting this issue. It seems like this issue has multiple components. We identified the driver side issue and have a fix for it, which will be released in an upcoming NVIDIA driver release. That fix allows the second monitor to work on KWin 6.2.4. However, Mutter needs some compositor side changes on top of the driver fix we have implemented. The required change can be found at https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4182.

Great news!  Thank you very much!

**Comment by gilvbp** [comment]
Fixed with new 570 driver.

**Comment by xhertan** [comment]
Hey @gilvbp, I know you closed this post, but I'm wondering if this has been fixed on  the gnome side. I am using KDE with the 570 driver right now and everything is working perfectly. One thing I noted on KDE is its performance is much better, not more stuttering artifacts on the desktop.

**Comment by gilvbp** [comment]
> Hey @gilvbp, I know you closed this post, but I'm wondering if this has been fixed on  the gnome side. I am using KDE with the 570 driver right now, and everything is working perfectly. One thing I noted on KDE is its performance is much better, not more stuttering artifacts on the desktop. 

It's still not fixed on Gnome. There's no solution for it yet. There's a fix that probably will be landed on 575, although it still needs a fix on the mutter side. They closed one MR (that worked) because what's not the right way to fix it. Right now, I'm using cosmic epoch, and it's working very fast and with zero issues.

**Comment by xhertan** [comment]
Thank you @gilvbp  for the update. Hopefully, we can get this solved in Gnome soon. But also the laggy performance we are observing in gnome.

**Comment by gilvbp** [comment]
> Thank you [@gilvbp](https://github.com/gilvbp) for the update. Hopefully, we can get this solved in Gnome soon. But also the laggy performance we are observing in gnome.

Hi @xhertan, I'm back to the gnome (seems to be fixed almost 100%). Check https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4182#note_2377250

**Comment by xhertan** [comment]
Hi @gilvbp, thank you for keeping me in the loop on this. It looks like I will get it fixed on time for Fedora 42.  Great!
